[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://beatscrest.onrender.com/api"
  VITE_STRIPE_PUBLISHABLE_KEY = "your-stripe-publishable-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist" 