services:
  - type: web
    name: beatcrest-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: your-db-host
      - key: DB_NAME
        value: beatcrest
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: FRONTEND_URL
        value: https://your-netlify-site.netlify.app 