services:
  - type: web
    name: beatcrest-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: your-mongodb-connection-string
      - key: FRONTEND_URL
        value: https://*.netlify.app 