services:
  - type: web
    name: beatcrest-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node simple-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://beatscrest.netlify.app
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false 